import type { Product } from "./types";

export const initialCatalog: Product[] = [
  {
    id: "P-001",
    name: "Leite Integral UHT",
    category: "Laticínios",
    unit: "caixa",
    price: 6.9,
    stock: 140,
    aliases: [
      "leite integral",
      "leite uht integral",
      "leite uht",
      "leite longa vida",
      "caixa de leite",
      "leite",
    ],
    status: "Ativo",
  },
  {
    id: "P-002",
    name: "Refrigerante Cola 2L",
    category: "Bebidas",
    unit: "unidade",
    price: 9.5,
    stock: 120,
    aliases: [
      "refrigerante cola 2l",
      "refrigerante cola",
      "cola 2l",
      "coca cola 2l",
      "coca-cola 2l",
      "coca cola",
      "coca-cola",
      "refri cola",
      "refrigerante",
      "coca",
    ],
    status: "Ativo",
  },
  {
    id: "P-003",
    name: "Arroz Tipo 1",
    category: "Mercearia",
    unit: "kg",
    price: 5.8,
    stock: 300,
    aliases: [
      "arroz tipo 1",
      "arroz branco tipo 1",
      "arroz branco",
      "arroz agulhinha",
      "arroz tipo um",
      "arroz",
    ],
    status: "Ativo",
  },
  {
    id: "P-004",
    name: "Feijão Carioca",
    category: "Mercearia",
    unit: "kg",
    price: 8.4,
    stock: 180,
    aliases: [
      "feijão carioca",
      "feijao carioca",
      "feijão carioquinha",
      "feijao carioquinha",
      "feijão",
      "feijao",
    ],
    status: "Ativo",
  },
  {
    id: "P-005",
    name: "Açúcar Refinado",
    category: "Mercearia",
    unit: "kg",
    price: 4.9,
    stock: 260,
    aliases: [
      "açúcar refinado",
      "acucar refinado",
      "açúcar branco",
      "acucar branco",
      "açucar",
      "açúcar",
      "acucar",
    ],
    status: "Ativo",
  },
  {
    id: "P-006",
    name: "Óleo de Soja 900ml",
    category: "Mercearia",
    unit: "unidade",
    price: 7.8,
    stock: 95,
    aliases: [
      "óleo de soja 900ml",
      "oleo de soja 900ml",
      "óleo soja",
      "oleo soja",
      "óleo de soja",
      "oleo de soja",
      "óleo",
      "oleo",
    ],
    status: "Ativo",
  },
  {
    id: "P-007",
    name: "Café Torrado 500g",
    category: "Mercearia",
    unit: "pacote",
    price: 18.9,
    stock: 80,
    aliases: [
      "café torrado 500g",
      "cafe torrado 500g",
      "café 500g",
      "cafe 500g",
      "café torrado",
      "cafe torrado",
      "pó de café",
      "po de cafe",
      "café",
      "cafe",
    ],
    status: "Ativo",
  },
  {
    id: "P-008",
    name: "Água Mineral 500ml",
    category: "Bebidas",
    unit: "fardo",
    price: 16,
    stock: 45,
    aliases: [
      "água mineral 500ml",
      "agua mineral 500ml",
      "fardo de água",
      "fardo de agua",
      "água mineral",
      "agua mineral",
      "água",
      "agua",
    ],
    status: "Ativo",
  },
  {
    id: "P-009",
    name: "Biscoito Cream Cracker",
    category: "Mercearia",
    unit: "pacote",
    price: 6.5,
    stock: 110,
    aliases: [
      "biscoito cream cracker",
      "bolacha cream cracker",
      "cream cracker",
      "biscoito salgado",
      "bolacha salgada",
      "biscoito",
      "bolacha",
    ],
    status: "Ativo",
  },
  {
    id: "P-010",
    name: "Detergente 500ml",
    category: "Limpeza",
    unit: "unidade",
    price: 3.2,
    stock: 160,
    aliases: [
      "detergente 500ml",
      "detergente neutro",
      "detergente líquido",
      "detergente liquido",
      "detergente cozinha",
      "detergente",
    ],
    status: "Ativo",
  },
];

export const getProductStatus = (stock: number): Product["status"] =>
  stock <= 50 ? "Baixo estoque" : "Ativo";
